FROM python:3.11-slim

# 作業デcxィレクトリ作成
WORKDIR /app

affffffff# 依存関係コピー＆インストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# プロジェクト用ファイルを全部コピー（初期は空だけど）
COPY . .

# 開発サーバーのポートを開ける
EXPOSE 8000

# デフォルトコマンドは bash にしておく（起動時は docker-compose 側で指定）
CMD ["bash"]
